[package]
name = "dhstore"
version = "0.0.1"
authors = [ "Remi Rampin <remirampin@gmail.com>" ]
repository = "https://github.com/remram44/dhstore"

[[bin]]
name = "dhstore"
doc = false

[dependencies]
log = "0.3"
sha1 = "0.2"
