name: Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-version: [stable, nightly]
        include:
          - os: macos-latest
            rust-version: stable
          - os: windows-latest
            rust-version: stable
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      id: rustup
      with:
        toolchain: ${{ matrix.rust-version }}
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run smoke test
      run: ./smoketest.sh
